version: "3.9"
services:
  postgreswasdiclient:
    hostname: postgreswasdiclient
    container_name: postgreswasdiclient
    image: "postgres:15.5"
    environment:
        POSTGRES_PASSWORD: multipass
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    
  #app:        
  #  ports: 
  #      - "4200:4200"
  #  build:
  #      context: .
  #      dockerfile: app/Dockerfile
  
  keycloak:
    hostname: keycloak
    container_name: keycloakwasdiclient
    depends_on:
     - postgreswasdiclient
    build:
      context: ./auth
      dockerfile: ./Dockerfile
    command: start --db postgres --hostname-strict false --hostname-strict-https=false --proxy edge --http-relative-path /auth --import-realm
    volumes:
   #   - ./auth/themes/:/opt/keycloak/themes
      - ./auth/import/:/opt/keycloak/data/import
  
  reverse-proxy:
    hostname: nginx
    container_name: nginx
    depends_on:
     - postgreswasdiclient
     - keycloak
    ports:
     - "80:80"
    build:
        context: ./reverse-proxy
        dockerfile: Dockerfile